export const urls = {
    CATEGORIES: 'api/mobile/categories/',
    SUB_CATEGORY: 'api/mobile/sub-category/',
    GET_MESSAGE_CATEGORY: 'api/mobile/message-categories',
    GOV_BODY: '/api/mobile/governing-bodies/',
    REGISTER_USER: '/api/user/register/',
    GET_ROOMS: '/api/room/get/rooms/user/',
    SEND_EMAIL_MESSAGE: '/api/mobile/email-messages/stor/',
    CHECK_AVAILABLE_ADMINS: '/api/admin/online/exist/',
    GET_FAQS: '/api/mobile/faq-categories/',
    UPDATE_FMC_TOKEN: '/api/mobile/update-fcm-token',
    NOTIFICATIONS: '/api/mobile/notifications',
    SETTINGS: '/api/mobile/settings',
    UPDATE_SITUATION: '/api/message/update/situation/',
}