export const appStrings = {
    homePage: "Գլխավոր էջ",
    fastConnect: "Արագ կապ",
    sendMessage: "Գրել նամակ",
    emailSuccess: "Էլեկտրոնային նամակը\n հաջողությամբ ուղարկվել է",
    emailError: "Ցավում ենք, ձեր նամակը չի \n ուղարկվել",
    emailMessage: "Էլ. նամակ",
    call: "Զանգ",
    pn: "Պաշտպանության նախարարություն",
    mip: "ՄԻՊ գրասենյակ",
    pnAndMip: "Պաշտպանության նախարարություն եվ ՄԻՊ գրասենյակ միասին",
    emptyMessages: 'Դուք դեռ չունեք ակտիվ նամակներ սեղմեք “նոր” կոճակը որպեսզի սկսեք',
    emptyMessagesInactive: 'Դուք դեռ չունեք ավարտված նամակներ սեղմեք “նոր” կոճակը որպեսզի սկսեք',
    active: 'Ակտիվ',
    inactive: 'Ավարտած',
    new: 'Նոր',
    message: 'Նամակ',
    emailMessageLarge: 'Էլեկտրոնային նամակ',
    pnAndMipTogether: 'Պաշտպանության նախարարություն եվ ՄԻՊ գրասենյակ միասին',
    emailErrorMessage: 'Մուտքագրած էլ. հասցեն անվավեր է',
    nameLastName: 'Անուն Ազգանուն*',
    emailAddress: 'Էլ. հասցե',
    number: 'Հեռախոսահամար*',
    numberError: 'Համոզվեք, որ հեռախոսահամարը ճիշտ է մուտքագրված',
    category: 'Կատեգորիա',
    on: 'Միացնել',
    off: 'Անջատել',
    notifications: 'Ծանուցումներ',
    notificationsSound: 'Ծանուցումների ձայնը',
    darkMode: 'Մուգ ռեժիմ',
    fontSize: 'Տառաչափ',
    calling: 'Զանգել',
    cancel: 'Չեղարկել',
    answerAndQuestions: 'հարց եվ պատասխան',
    removeAll: 'Ջնջել բոլորը',
    numbersIsNotAvailable: 'Չկան ակտիվ համարներ։',
    hey: 'Ուշադրություն',
    unableInternet: 'Չկա ինտերնետ հասանելիություն։',
    operatornotFound: 'Այս պահին չկան ակտիվ օպերատորներ։',
    retry: 'Խնդրում ենք փոձել մի փոքր ուշ։'
}